Final merge of alpha into main (#12)
* Update instancegenerator.py to allow for more liberal player 2 answer parsing

* bugfix in instancegenerator.py to initialize target names as list

* Update master.py to allow liberal parsing of player 2 answers in the scorer

* Update instances.json with player 2 options (and add formatting)

* fix typo in master.py

* wordle: handling of contextexceeded error, updated evaluation for classic variant

* make reference game backwards compatible for scoring

* Feat/multimodal backend (#93)

* together.ai, llama-3, Gemini, Cohere, OpenAI (gpt-4o) multimodal backends
* multimodal reference game with AED, CLEVR, DOCCI  images
* normalized message encoding by commercial backends

* New model entries for May 2024 (#92)

* Add HF model entries: Swallow-70b-instruct-v0.1, Phi-3-mini-128k-instruct, gemma-1.1-2b-it, gemma-1.1-7b-it, Starling-LM-7B-beta, codegemma-7b-it, recurrentgemma-2b-it
* Add llama.cpp model entries: Meta-Llama-3-70B-Instruct-GGUF-q4, Meta-Llama-3-70B-Instruct-GGUF-q8 (needs testing due to split GGUF)
* Add handling of additional files for sharded GGUF to llamacpp_api.py; Add 'additional_files' key to Meta-Llama-3-70B-Instruct-GGUF-q8 entry
* Add c4ai-command-r-plus-GGUF-q4 and c4ai-command-r-plus-GGUF-q8 model registry entries
* Add ensure_alternating_roles call to LlamaCPPLocalModel.generate_response()

* fix Google api

* fix Google api

* Gemini-1.0-vision model

* Google multimodal backend: upload images from URL

* transcribe: show images on html transcribe when possible; add IMAGE_ROOT env var (if needed)

* adjusted model names for Llama-3 using Anyscale, Together, Gemini model versions

* initial template for the assistant

* Update ex_location.json

Extended thee amount of MAIN-ACTIONS to test some stuff

* Update pc.py

First codes to generate randomized instances automatically within the prompts.
Included for now are:
start of game
choosing a date (a NPC)
begin of the level (location + first action)

To-Do:
Include prompt/generation for following actions

* now prompts look more pythonish :p

* Filled in the further_actions function

* Adding NPC part of the code with a bit of addition of game_state points. Also minor typo in ex_NPC_sheet

* Moving sheets to resources

* Test imge (#1)

* First ideas so save playthrough

* Update instancegenerator.py

Pain and suffering :)

* Update master.py

* transcribe: show images from http urls directly

* initial prompt templates

* generated utils.py (#2)

 Update instancegenerator.py

Pain and suffering :)
 First attempt of game.py

Need to modify the ePlayr classes later on, after w efully understand how th master.py works

* Update master.py

* Create utils.py

* Update instancegenerator.py

* initial prompt templates

* Fixing branch

    pick aaaa53f Update instancegenerator.py
    pick 052a97d First attempt of game.py

* Update instancegenerator.py

Pain and suffering :)

* First attempt of game.py

* Create utils.py

* Create instancegenerator.py

---------

Co-authored-by: altarluser <altarluser@gmail.com>
Co-authored-by: Jerycho Pasniczek <pasniczek@uni-potsdam.de>

* variables in each template are now dynamic

* Update assistant.template

* Update npc.template

* Update instancegenerator.py

* Added the gameflow, hopefully it's in the right place. Not sure about the turns yet

* Multimodal reference game instaces: pentomino, static target for photo experiments, updated CLEVR instances based on similarity

* static target images

* Create key.json

* Create key.json

* Adding inserting API key (to every player) to allow the conversation to happen

* spdrun

* speeeed

* Adding working instance generator and generated instance

* update libraries for multimodal map navigation

* Adding npcs to instancegenerator.py

* ADding generated instances.json

* Adding comment for the future

* added Claude-3.5-Sonnet

* I am adding what @Arellias implemented locally and what I have added to make it almost work (for some reason it tells that
NotImplementedError: ('No game benchmark for:', 'dating_simulator')

* I am adding what @Arellias implemented locally and what I have added to make it almost work (for some reason it tells that
NotImplementedError: ('No game benchmark for:', 'dating_simulator')

* just adding key file so the game runs

* Update ex_NPC_sheet.json

* Update ex_location.json

* add multimodal backend (#96)

* added MatchIt, Map Navigation games

* Adding everything discussed with Nicolas, everything is broken but that's the point

* Adding key files to fill if we ever wanna run it

* Update ex_NPC_sheet.json

* Update ex_location.json

* trying to make it work

* further

* Adding players for informative meaning

* Adding more commments and explanations and old_code.py just to keep track of the changes made

* more changes to clean up the code

* ğ

* ğ

* patterns are now in instance_generator.py and fixed the setup in master.py and the corresponding variables in master.py as well

* updating files and removing

* updating comments and spare code

* your mom

* new templates

* updating master with comments and slight code changes

* pushing changes and commments on master again

* Pushing changes of GM not to lose all that was done and commented

* to make it clear:
i = level
j = main_action
k = subaction

* clarifying the code more, adding more clear prompts and structure

* fixing silly mistakes

* =further changes and filling templates

* A lot of things added, still GM not finished, more consultation and changes needed

* Added a task (todo) list, adding more code (GM is almost working and has 99% of game logic), adding templates

* Added a task (todo) list, adding more code (GM is almost working and has 99% of game logic), adding templates

* Added a task (todo) list, adding more code (GM is almost working and has 99% of game logic), adding templates

* Added a task (todo) list, adding more code (GM is almost working and has 99% of game logic), adding templates

* commenting legacy code

* Update TASK_LIST.md

* Delete key.txt

* Delete key.json

* Update .gitignore

* instance gen with assistant

* Delete games/datingsim/readable.py

* quick task and formatting update

* Edited the RegEx pattern

* Update master.py (#3)

Added methods to 
1) check if th game should continue
2) if the response of Player('s) is correct

* added Text world game versions

* added/updated README files for all games

* Adding new game skeleton and transferring removed code to old_code

* Model additions (#97)

* Add Qwen2-7B-Instruct, Qwen2-72B-Instruct, aya-23-8B and aya-23-35B to model registry

* Add requires_api_key key to aya-23-8B and aya-23-35B model registry entries

* Change required transformers version to 4.41.2

* Add gemma-2-9b-it and gemma-2-27b-it to model registry; Update required transformers version for gemma-2 models

* Change required torch version to 2.1.1 to support Gemma-2 models; Change Gemma-2 model registry entries' eos_to_cull to "<end_of_turn>\n<eos>"

* Change HF backend output EOS culling to use regEx; Change Gemma2 model entry eos_to_cull to regEx pattern

* Further changes adapting to new solution (adjusted player, added and removed some code, logging mostly covered)

* Update instancegenerator.py

Changed the instance generation according to the new game design

* Create testfile.json

changed the dataset format. as far as i understood ot, each dataset in here represents a new experiment. hence each experiment has it's name as well as the data we need for it

* Update utils.py

so far commented out all the functions we (sadly) don't need anymore

* Small changes before proceeding

* Cleaning up and fixing issues

* Generated first version for  initial prompts

* Adding working code (only problem with backends.openai_compatible_api connection error

* Some minor changes

* added replacement of actual char sheet within th prompts

* debugging?

* debugged? ._.

* Generated from Arellia's code

* adding log

* new gamescorer (#4)

* Working Game Version - Needs further modification (#5)

* A working master file. Games run. Needs some filing.

* Added more characters and their origins.

* Forgot to save.

* Pre-defined the experiment. Only need to fill in characters and include sth in instancegenerator.py for the last experiment

* Filled out the same-sex experiments

* Deleted my API key.. once again ._.

* Cleaned the measter files.

* Cleaned the master files.

* Added end-line marker

* deleted unused code

* Included the validity check again

* Changed turn definition. Now each turn is defined by one utterance of a player: player1 says sth = 1 turn. Next turn: player 2 says sth. Turn 3: player1 speaks etc.

* Changed the sentimed to a binary decision as discussed

* Included the ending of game based on if the players found an agreement together or not. and their logging information

* Update README.md

* updated gamescorer, new instances.json and tweaked gamemaster to make it in sync with scorer

* Update template

* Update template

* added token restriction

* Update instance generator

* Deleting dating_simulator and making minor changes on master.py of datingsim

* Deleting dating_simulator and making minor changes on master.py of datingsim

* Changing the player and master to remove warnings

* added qwen2 to the model_registry

* fixed typo in the agreement pattern and a bug in saving completed turns. also prompts are recent

* included reprompting - added stuff we need for that and included the check of token length

* new instances

* fixed a bug

* Minor changes

* Adding prompt to move files from folder to folder (keeping the folder inner structure so all subfolders etc) and fixing one typo

* finalised first experiments

* New instances based on new testfile

* added new action_types and fixed metrics

* fixed a typo

* fixed metrics

* debugged

* your mom

* Add Llama-3-SauerkrautLM-70b-Instruct to the model registry (#102)

* Added GPT-4o-mini to model registry

* Add Meta-Llama-3.1-8B-Instruct and Meta-Llama-3.1-70B-Instruct to model registry; Update required transformers version to 4.43.1 (#103)

* Add Mistral-Large-Instruct-2407 to model registry (#106)

* Llama-3.1-405B on Together.ai

* Logging and scoring documentation update (#107)

* Update documentation to current records directory structure
* Add custom logging/scoring info
* Add a few docstrings/comments
* Add transcript section
* Add HTML transcription of dicts without images
* Finish logging_and_scoring.md; Use os.sep in evalutils.py parse_directory_name to make overview table generation OS-agnostic

* changing transcript_utils to include messages in json format that are not itended to show images and adjust games to properly show images each turn (#108)

* add release-dates and open-weight flag (#109)

* add release dates and open-weight flag

* change to open_weight

* add parameters key

* update 3.5 sonnet param size

* update mistral params

* add estimated params key [optional]

* Add gemma-2-2b-it model registry entry (#111)

* gpt-4o August 2024 model

* working version with new agreement types (#7)

* added new agreement types
to check_for_agreement() and adjusted update_sentiment pattern accordingly

* rervised initial prompts

* fixed a typo in instance gen and run it for new prompts

* fixed typos in check_for_agreement() and uploaded clean log to look at

* Update initialprompt_playerA.template

* Update initialprompt_playerB.template

* Updating instances according to last PR

* Gemini 1.5 Pro New Model

* added missing details to GPT-4o and Gemini 1.5 models

* Fixing master which caused result saving faulty

* Finalized Reprompting (#8)

* Inserted reprompt bc I messed up the master version in the other branch and cleaned up the code a bit

* Changed the prompt a teeny bit (added the 'shouting)'

* last clean up before I deal with benchmark - including the repromp

* just adding endline

* Removing spare code to clean up

* revised the aim of the goal, updated the logs and fully working gamescorer accordingly

* fixed a bug in scorer

* fixed a bug in scorer

* added two logs for aborted cases

* A "quick" and detailed guide how to go through clembench evaluation with the least pain possible

* Minor update to the cheat_sheet to make it more readable

* Update for benchmarkeval in cheat_sheet.md

* Cosmetic changes to cheat_sheet.md

* completed_turns fixed, and more readable logging

* added reprompt parameter to setup() and fixed typo, then ran instancesgen

* fixed typo

* Update model_registry.json

* Update instancegenerator.py

* cleaned the code: ditched valid and request counters

* small correction regarding max number of turns

* updated gamescorer according to the new proposal + fixed the bug in "already agreed" cases

* minor logging fix

* Changed logs to differentiate invalid formats

* Added the logs (?)

* Fixed the logging

* added new turn logs and fixed a bug in benchmark

* Fixed the error message. Added answer as return value in check_validity_reprompt.  Comments might need to be adapted.

* Removing location and set_of_actions from instancegenerator.py

* Removing location and set_of_actions from instancegenerator.py

* Adding datasets for modes, just in case we need them

* Definded all the experiments and changed the reesources and prompts respectively.

* Adaptde mastr.py

* renamed the file

* fix encoding in openai-backend; update and add documentation notebooks (#115)

* fix superfluous (and problematic) encoding of text messages in text-only models

* update prototyping notebook to work properly with registry

* add one more notebook aimed at easing getting into writing games

* plotting the generated graphs next to the target graph (#121)

* fix scoring for multimodal_map_graphs: changed the name of the metric and the value to be 0-100 range

* Debugged last bugs

* added some models for experiments

* Create placeholder.txt

* Add files via upload

* Add files via upload

* Delete results/placeholder.txt

* Adding llama results

* gemma and qwen results

* openchat results

* Quick update what i used to generate plots

* All the generated results

* quick fix for out of retries

* Updated results

* checking for nan warnings

* checking for error

* clensing for now

* adding results

* eval results

* Update EOS culling to proper regEx substitution (#120)

* Change EOS culling in llamacpp_api.py to use regEx substitution; Add model_registry_eos_check.py script for checking model registry entry EOS for regEx; Update hf/llamacpp model entries' eos_to_cull to expected regEx (escaping |): falcon-7b-instruct, falcon-40b-instruct, oasst-sft-4-pythia-12b-epoch-3.5, openchat_3.5, Yi-34B-Chat, SUS-Chat-34B, openchat-3.5-0106, openchat-3.5-1210, Nous-Hermes-2-Mixtral-8x7B-DPO, Smaug-72B-v0.1, Smaug-34B-v0.1, Qwen1.5-7B-Chat, Qwen1.5-72B-Chat, Phi-3-mini-128k-instruct, Starling-LM-7B-beta, Qwen2-7B-Instruct, Qwen2-72B-Instruct, Llama-3-SauerkrautLM-70b-Instruct, aya-23-8B, aya-23-35B, Meta-Llama-3.1-8B-Instruct, Meta-Llama-3.1-70B-Instruct, Qwen1.5-0.5B-Chat-GGUF-q8, CapybaraHermes-2.5-Mistral-7B-GGUF-q4, CapybaraHermes-2.5-Mistral-7B-GGUF-q5, CapybaraHermes-2.5-Mistral-7B-GGUF-q5-k-s, openchat_3.5-GGUF-q5, Meta-Llama-3-70B-Instruct-GGUF-q4, Meta-Llama-3-70B-Instruct-GGUF-q8, c4ai-command-r-plus-GGUF-q4, c4ai-command-r-plus-GGUF-q8; Update model registry documentation on eos_to_cull regEx

* Add raw test results

* Add v1.6 comparison requests.json files and convert json files to readable indented format (for episode 0 of all test experiments)

* Remove testing data

* Update howto_run_games_locally.md

* fix bug in textmapworld-specific room

* Updated results - easy/diffult experiments for particular features deleted

* Updated results - easy/difficult experiments deleted, renaming experiments by removing 'medium' word (default)

* Adding previously ignored files

* registered openchat via llamacpp

* revised openchat details

* added instructions on how to run openchat model

* deleting reduntant resource files and temporarily commenting out mismatch agreements to make transcripts look cleaner and plots accurate

* Adding minor changes cleaning up the code, fixing comments, formatting etc

---------

Co-authored-by: Anne Beyer <anne.beyer@mailbox.org>
Co-authored-by: kranti <kranti.chalamalasetti@uni-potsdam.de>
Co-authored-by: Sherzod Hakimov <sherzodhakimov@gmail.com>
Co-authored-by: Jonathan Jordan <knawurzelkopp@hotmail.de>
Co-authored-by: Philipp Sadler <philipp.sadler@gmail.com>
Co-authored-by: altar <44545494+altarluser@users.noreply.github.com>
Co-authored-by: Imge Yüzüncüoglu <86414587+imgeyuez@users.noreply.github.com>
Co-authored-by: altarluser <altarluser@gmail.com>
Co-authored-by: Arellias <i.yuezuencue@gmail.com>
Co-authored-by: kushal-10 <83510614+kushal-10@users.noreply.github.com>
Co-authored-by: David Schlangen <david.schlangen@uni-potsdam.de>
Co-authored-by: yanweiser <47057387+yanweiser@users.noreply.github.com>